<?php

/**
 * Implements hook_appstore_stores_info
 *
 * Add the levelten_apps server
 */
function vih_apps_apps_servers_info() {
  $profile = variable_get('install_profile', 'standard');
  $info =  drupal_parse_info_file(drupal_get_path('profile', $profile) . '/' . $profile . '.info');
  return array(
    'vih' => array(
      'title' => 'VIH',
      'description' => "Apps from VIH Interactive",
      'manifest' => 'http://localhost/openapps/app/query/Production',
      'profile' => $profile,
      'profile_version' => isset($info['version']) ? $info['version'] : '7.x-1.x',
      'server_name' => $_SERVER['SERVER_NAME'],
      'server_ip' => $_SERVER['SERVER_ADDR'],
    ),
  );
}
